
name: Build

on:
  push:
    branches: [ master, main ]

jobs:
  build:
    runs-on: ubuntu-20.04
    permissions:
      contents: read
      packages: write
    env:
      GHCR_REGISTRY: ghcr.io
      IMAGE: ghcr.io/bulatinco/devops-spring-k8s2/webapp

    steps:
      - uses: actions/checkout@v2
      - run: openssl enc -d -aes256 -pbkdf2 -pass pass:${{ secrets.DECRYPT_PASS}} -in Dockerfile.enc -out Dockerfile
      - uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ${{ env.GHCR_REGISTRY }}
          repository: ${{ env.IMAGE }}
          tag_with_ref: true
